const PROJECTS = [
  {
    id: 1,
    code: 'SHOP_FLOW',
    title: 'E-COMMERCE SHOP',
    desc: 'High-performance e-commerce platform with Admin Dashboard, cart state management, and zero-lag React Router navigation.',
    tags: ['#React', '#MongoDB', '#MERN'],
    bg: 'bg-neon',
    live: 'https://umer-shop-flow.netlify.app/',
    github: 'https://github.com/umermansoor124/E-Commerce-Shop-Flow',
  },
  {
    id: 2,
    code: 'NEXUS_CHAT',
    title: 'NEXUS CHAT',
    desc: 'Full-stack real-time chat application with secure auth, optimized DB queries, deployed on Railway and Netlify.',
    tags: ['#React', '#Node.js', '#Socket'],
    bg: 'bg-blue',
    live: 'https://nexuschats-website.netlify.app/',
    github: 'https://github.com/umermansoor124/NexusChat',
  },
  {
    id: 3,
    code: 'FIT_TRACK',
    title: 'FITNESS TRACKER',
    desc: 'MERN health analytics app to monitor daily workouts, health metrics, and progression with interactive dashboards.',
    tags: ['#React', '#MongoDB', '#Tailwind'],
    bg: 'bg-orange',
    live: 'https://umer-fitness-tracker.netlify.app/',
    github: 'https://github.com/umermansoor124/FITNESS-TRACKER',
  },
  {
    id: 4,
    code: 'AURA_HW',
    title: 'AURA HEADPHONE',
    desc: 'Cinematic luxury headphone brand site with scrollytelling, canvas animations, and high frame-rate rendering via Vite.',
    tags: ['#JavaScript', '#Canvas', '#Vite'],
    bg: 'bg-purple',
    live: 'https://umerheadphone.netlify.app/',
    github: 'https://github.com/umermansoor124/UMER-HEADPHONE',
  },
  {
    id: 5,
    code: 'DEEP_BLACK',
    title: 'DEEP BLACK PERFUME',
    desc: 'Dark luxury perfume brand website with immersive scroll-based animations and premium aesthetic design.',
    tags: ['#JavaScript', '#CSS', '#WebDesign'],
    bg: 'bg-red',
    live: 'https://umerperfume.netlify.app/',
    github: 'https://github.com/umermansoor124/UMER-PERFUME',
  },
  {
    id: 6,
    code: 'JARVIS_AI',
    title: 'JARVIS & ALEXA',
    desc: 'Python-powered AI voice assistants with Web Speech API integration for voice commands and desktop automation.',
    tags: ['#Python', '#AI', '#SpeechAPI'],
    bg: 'bg-yellow',
    live: null,
    github: 'https://github.com/umermansoor124/JARVIS',
  },
  {
    id: 7,
    code: 'REACT_PORT',
    title: 'REACT PORTFOLIO',
    desc: 'Bespoke high-end portfolio with neo-brutal design, custom pointer physics, spider cursor, and fluid animations.',
    tags: ['#React', '#UI', '#Animation'],
    bg: 'bg-neon',
    live: 'https://umer-mansoor-portfolio.netlify.app/',
    github: 'https://github.com/umermansoor124/Umer-React-Portfolio',
  },
];

export default PROJECTS;